[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.armv7-unknown-linux-musleabihf]
linker="arm-linux-musleabihf-gcc"
# 或者执行这个也行
# rustflags = ["-C","linker=/usr/arm-linux-musleabihf-cross/arm-linux-musleabihf/bin/ld"]
[target.aarch64-unknown-linux-gnu]
linker="aarch64-linux-gnu-gcc"
[target.aarch64-unknown-linux-musl]
linker="aarch64-linux-musl-gcc"